export const FIELD_TYPES = {
	TEXT: 'text',
	PASSWORD: 'password',
	IP: 'ip',
	CIDR: 'cidr',
	SELECT: 'select',
	TIMEZONE: 'timezone',
	BOOLEAN: 'boolean',
	NUMBER: 'number',
	IP_LIST: 'ip-list',
	HOST_LIST: 'host-list',
	GENERIC_RANGE: 'generic-range',
	GENERIC_SELECT: 'generic-select',
	MESSAGE: 'message',
	FILE_UPLOAD: 'file_upload',
	GRID: 'grid',
	NOVL: 'novl',
	EDITOR: 'editor',
	SLIDER: 'slider',
	HYPERLINK: 'hyperlink',
	TEXTAREA: 'textarea',
	DEPENDENT_LIST: 'dependent-list',
	SUBSECTIONS_TUPLE: 'subsections-tuple'
};
